title: Bus-bike Multimodality Project
logo: /assets/img/logo.png
description: Geospatial Data Science in Python: Final Project.
show_downloads: false
repository: golete/bike-bus-multimodal
google_analytics:
remote_theme: pages-themes/minimal
plugins:
